// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLa8YFx6xJt_Emuyn_3ltJcr-pAcDco8s',
    appId: '1:162296019822:web:30950d1d49445a160bdf7f',
    messagingSenderId: '162296019822',
    projectId: 'poloniex-market',
    authDomain: 'poloniex-market.firebaseapp.com',
    storageBucket: 'poloniex-market.appspot.com',
    measurementId: 'G-Q3Q3E89GNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsrx6ZXLJ5zG5gRbCn5VNuvBT6yjDuLlk',
    appId: '1:162296019822:android:e5b5c2bb1089284f0bdf7f',
    messagingSenderId: '162296019822',
    projectId: 'poloniex-market',
    storageBucket: 'poloniex-market.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD45H-roBln9bALnZ8vhYljFDjbkjtT6AQ',
    appId: '1:162296019822:ios:f38fccfca94d8b750bdf7f',
    messagingSenderId: '162296019822',
    projectId: 'poloniex-market',
    storageBucket: 'poloniex-market.appspot.com',
    iosBundleId: 'com.example.poloniexApp',
  );
}
